---
apiVersion: v1
kind: Namespace
metadata:
  name: reloader-example
  annotations:
    # annotations below will be propagated to all resources
    # managed by the scribe controller
    scribe.anza-labs.dev/annotations: |
      reloader.stakater.com/auto=true
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: nginx
  namespace: reloader-example
spec:
  selector:
    matchLabels:
      app: nginx
  template:
    metadata:
      labels:
        app: nginx
    spec:
      containers:
      - name: nginx
        image: nginx
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
